# -*- coding: utf-8 -*-

DEFAULT_TOOLS = [
    {'country': u'Belgium',
        'sector': u'Coiffure',
        'sector_description': u'hairdressing',
        'language': u'fr',
        'url': "https://client.oiraproject.eu/be/coiffure/oira-coiffure"},
    {'country': u'Belgium',
        'sector': u'Kappers',
        'sector_description': u'hairdressing',
        'language': u'nl',
        'url': "https://client.oiraproject.eu/be/coiffure/oira-kappers"},
    {'country': u'Bulgaria',
        'sector': u'Воден транспорт ',
        'sector_description': u'water transport',
        'language': u'bg',
        'url': "https://client.oiraproject.eu/bg/voden-transport/voden-transport"},
    {'country': u'Bulgaria',
        'sector': u'Въздушен транспорт',
        'sector_description': u'air transport',
        'language': u'bg',
        'url': "https://client.oiraproject.eu/bg/vzdushien-transport/vazdushen-transport"},
    {'country': u'Bulgaria',
        'sector': u'Горско стопанство',
        'sector_description': u'forestry',
        'language': u'bg',
        'url': "https://client.oiraproject.eu/bg/gorsko-stopanstvo/gorsko-stopanstvo"},
    {'country': u'Bulgaria',
        'sector': u'Далекосъобщения',
        'sector_description': u'telecommunications',
        'language': u'bg',
        'url': "https://client.oiraproject.eu/bg/dalekosaobshteniya/dalekosaobshteniya"},
    {'country': u'Bulgaria',
        'sector': u'Държавно управление',
        'sector_description': u'public administration',
        'language': u'bg',
        'url': "https://client.oiraproject.eu/bg/darzhavno-upravlenie-1/darzhavno-upravlenie"},
    {'country': u'Bulgaria',
        'sector': u'Медико-социалн  и грижи с настаняване',
        'sector_description': u'residential care activities',
        'language': u'bg',
        'url': "https://client.oiraproject.eu/bg/mediko-sotsialni-grizhi-s-nastanyavane/"},
    {'country': u'Bulgaria',
        'sector': u'Образование',
        'sector_description': u'education',
        'language': u'bg',
        'url': "https://client.oiraproject.eu/bg/obrazovanie-1/obrazovanie"},
    {'country': u'Bulgaria',
        'sector': u'Производство на изделия от каучук',
        'sector_description': u'manufacture of rubber products',
        'language': u'bg',
        'url':"https://client.oiraproject.eu/bg/proizvodstvo-na-izdeliya-ot-kauchuk-i-plastmasi/proizvodstvo-na-izdeliya-ot-kauchuk"},
    {'country': u'Bulgaria',
        'sector': u'Производство на изделия от пластмаси  ',
        'sector_description': u'manufacture of plastic products',
        'language': u'bg',
        'url': "https://client.oiraproject.eu/bg/proizvodstvo-na-izdeliya-ot-kauchuk-i-plastmasi/proizvodstvo-na-izdeliya-ot-plastmasi"},
    {'country': u'Bulgaria',
        'sector': u'Производство на облекло',
        'sector_description': u'manufacture of wearing apparel',
        'language': u'bg',
        'url': "https://client.oiraproject.eu/bg/proizvodstvo-na-obleklo/proizvodstvo-na-obleklo"},
    {'country': u'Bulgaria',
        'sector': u'Производство на химични продукти',
        'sector_description': u'manufacture of chemical products',
        'language': u'bg',
        'url': "https://client.oiraproject.eu/bg/proizvodstvo-na-khimichni-produkti/proizvodstvo-na-khimichni-produkti-1"},
    {'country': u'Bulgaria',
        'sector': u'Строителство',
        'sector_description': u'construction',
        'language': u'bg',
        'url': "https://client.oiraproject.eu/bg/stroitelstvo/stroitelstvo"},
    {'country': u'Cyprus',
        'sector': u'Εργασίες Γ  ραφείου - Δημόσια Διοίκηση',
        'sector_description': u'office work',
        'language': u'el',
        'url': "http://client.oiraproject.eu/cy/civil-service/demosia-dioikese"},
    {'country': u'Cyprus',
        'sector': u'Κλάδος εταιρειών τροφοδοσίας',
        'sector_description': u'catering',
        'language': u'el',
        'url': "https://client.oiraproject.eu/cy/etaireies-trophodosias-catering/klados-etaireion-trophodosias-catering"},
    {'country': u'Cyprus',
        'sector': u'Κομ μωτήρια',
        'sector_description': u'hairdressing',
        'language': u'el',
        'url': "http://client.oiraproject.eu/cy/hairdressers/cyprus_hairdressers_el"},
    {'country': u'Cyprus',
        'sector': u'Κρεοπωλεια',
        'sector_description': u'butchers',
        'language': u'el',
        'url': "https://client.oiraproject.eu/cy/kreopoleia/kreopoleia"},
    {'country': u'Czech Republic',
        'sector': u'KADEŘNICKÉ SLUŽBY',
        'sector_description': u'hairdressing',
        'language': u'cs',
        'url': "https://client.oiraproject.eu/cz/kadernicke-sluzby/kadernicke-sluzby"},
    {'country': u'Pan-European',
        'sector': u'Cleaning',
        'sector_description': u'',
        'language': u'en',
        'url': "https://client.oiraproject.eu/eu/eu-cleaning/eu-cleaning"},
    {'country': u'Pan-European',
        'sector': u'Leather and tanning',
        'sector_description': u'',
        'language': u'en',
        'url': "http://client.oiraproject.eu/eu/leather-tanning/leather-tanning-draft-risk-assessment-tool/start"},
    {'country': u'Pan-European',
        'sector': u'Private Security',
        'sector_description': u'',
        'language': u'en',
        'url': "https://client.oiraproject.eu/eu/eu-private-security/private-security-eu"},
    {'country': u'France',
        'sector': u'Restauration traditionelle',
        'sector_description': u'catering sector',
        'language': u'fr',
        'url': "https://client.oiraproject.eu/fr/restauration/restauration-traditionnelle/"},
    {'country': u'France',
        'sector': u'Transport routier',
        'sector_description':  'road transport',
        'language': u'fr',
        'url': "http://client.oiraproject.eu/fr/transportroutier/transporoutier-2-parametres"},
    {'country': u'Greece',
        'sector': u'ΚλάδÎ ¿ς εταιρειών τροφοδοσίας',
        'sector_description':  'catering sector',
        'language': u'el',
        'url': "https://client.oiraproject.eu/gr/catering/ergaleio-oira-gia-tin-ektimisi-kindynoy-ston-klado-ton-etaireion-trofodosias-catering"},
    {'country': u'Greece',
        'sector': u'Κλάδος εμπορικών καταστημάτω',
        'sector_description': u'commercial shops',
        'language': u'el',
        'url': "https://client.oiraproject.eu/gr/commercial-shops/emporika-katastimata"},
    {'country': u'Greece',
        'sector': u'Κλάδος κομμωτηρίων',
        'sector_description': u'hairdressing',
        'language': u'el',
        'url': "https://client.oiraproject.eu/gr/hairdressers/hairdressing-salons"},
    {'country': u'Latvia',
        'sector': u'Darbs birojā',
        'sector_description': u'office work',
        'language': u'lv',
        'url': "https://client.oiraproject.eu/lv/latvia-test/darbs-biroja/@@login?came_from=https%3A%2F%2Fclient.oiraproject.eu%2Flv%2Flatvia-test%2Fdarbs-biroja%2F"},
    {'country': u'Latvia',
        'sector': u'Izglītības iestādes',
        'sector_description': u'educational establishments',
        'language': u'lv',
        'url': "https://client.oiraproject.eu/lv/latvia-test/izglitibas-iestades-1"},
    {'country': u'Lithuania',
        'sector': u'Automobilių remontas',
        'sector_description':  'car repair',
        'language': u'lt',
        'url': "https://client.oiraproject.eu/lt/lt-test-sector/automobiliu-remontas"},
    {'country': u'Netherlands',
        'sector': u'Generic sector',
        'sector_description': u'',
        'language': u'en',
        'url': "https://client.oiraproject.eu/nl/generic/generic-tool-in-english"},
    {'country': u'Portugal',
        'sector': u'Cabeleireiro',
        'sector_description': u'hairdressing',
        'language': u'pt',
        'url': "https://client.oiraproject.eu/pt/cabeleireiro/cabeleireirofinal"},
    {'country': u'Spain',
        'sector': u'Adoberies',
        'sector_description': u'leather & tanning',
        'language': u'ca',
        'url': "https://client.oiraproject.eu/es/adoberies/adoberies"},
    {'country': u'Spain',
        'sector': u'Autoescuelas',
        'sector_description': u'driving schools',
        'language': u'es',
        'url': "https://client.oiraproject.eu/es/autoescuelas/autoescuelas"},

    # Tools still under development
    {'country': u'Pan-European',
        'sector': u'Live performance',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Pan-European',
        'sector': u'Cleaning',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Pan-European',
        'sector': u'Maritime transport',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Pan-European',
        'sector': u'Hairdressing',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Belgium',
        'sector': u'Woodworking',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Bulgaria',
        'sector': u'21 tools, various sectors',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Greece',
        'sector': u'Butchers',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Greece',
        'sector': u'Bakeries',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Greece',
        'sector': u'Woodworking workshops',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Greece',
        'sector': u'Pharmacies',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Greece',
        'sector': u'Laundry sector',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Greece',
        'sector': u'Office work',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Greece',
        'sector': u'Working in offices',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Latvia',
        'sector': u'Educational establishments',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Latvia',
        'sector': u'Agriculture',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Lithuania',
        'sector': u'Woodworking',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Lithuania',
        'sector': u'Working in offices',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Malta',
        'sector': u'Working in offices',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Portugal',
        'sector': u'Hairdressing',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Portugal',
        'sector': u'Road transport',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Portugal',
        'sector': u'Leather and tanning',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Slovenia',
        'sector': u'Working in offices',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Slovenia',
        'sector': u'Generic',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Slovenia',
        'sector': u'Cleaning',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Slovenia',
        'sector': u'Hairdressing',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Slovenia',
        'sector': u'Psychosocial',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Slovenia',
        'sector': u'Road transport',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Slovenia',
        'sector': u'Woodworking',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Spain',
        'sector': u'Hairdressing',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
    {'country': u'Spain',
        'sector': u'Road transport',
        'sector_description': u'still under development',
        'language': u'',
        'url': ""},
]
